### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jinwoo1225** [Tutor2Tutee/T2T-GO#1]
- [ ] authenticate by JWT token
- [ ] route API to t2t
- [ ] enable static serve
- [x] use validator
